### ISSUE TITLE
Action Mode tip destroys itself when changing font

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Clipjump#83]
http://clipjump.sourceforge.net/#comment-2152925014
http://aviaryan.in/blog/clipjump/getting-back-to-clipjump.html#comment-2108563615

FIX - 
1. Use a specialised library like TT
2. Use a GUI (like [PleasentNotify](http://ahkscript.org/boards/viewtopic.php?t=6056))

**Comment by hoppfrosch** [comment]
Don't know whether this is a related bug - but it also has to do with Action mode problems:
[pressing [Ctrl] + [Shift] + [A], but nothing happens](http://www.autohotkey.com/board/topic/91488-clipjump-the-ultimate-clipboard-manager-updated-210515/page-58#entry726292)

**Comment by hoppfrosch** [comment]
Don't know whether this is a related bug - but it also has to do with Action mode problems:
[pressing [Ctrl] + [Shift] + [A], but nothing happens](http://www.autohotkey.com/board/topic/91488-clipjump-the-ultimate-clipboard-manager-updated-210515/page-58#entry726292)

**Comment by aviaryan** [comment]
Yes that is the same bug. 

Quoting from http://aviaryan.in/blog/clipjump/getting-back-to-clipjump.html#comment-2108563615

" Since the new version, I've noticed that the Action Mode tooltip isn't working. On both my work PC (Win 8.1 Enterprise) and personal PC (Win 8.1 Home edition), when I press the Ctrl+Shift+A, the tooltip flashes but disappears. If I press "e" or any of the other hotkeys, the cooresponding action happens, but the tooltip is just not working. "

**Comment by hoppfrosch** [comment]
It occurs on my machine as well ...
AutoHotkey : 			v1.1.22.03 Unicode 32-bit

**Comment by aviaryan** [comment]
I am also using 1.1.22.03 (Win 8.1 x64) but I am not having any problems.

Have you tried running Clipjump v11.6.1 with AHK 1.1.22.03 ? Download it from http://sourceforge.net/projects/clipjump/files/Clipjump_11.6.1.zip/download or https://github.com/aviaryan/Clipjump/tree/v11.6.1

**Comment by hoppfrosch** [comment]
http://sourceforge.net/projects/clipjump/files/Clipjump_11.6.1.zip/download:  does not work as well, same behaviour


-------------------
Hint: clipjump.ahk (from this zip) does not run out of the box, due to following error (no need for fixing, just a hint to avoid in future versions)

---------------------------
Clipjump.ahk
---------------------------
Error in #include file "D:\Temp\Clipjump\lib\aboutgui.ahk":
     Can't load icon.

Specifically: icons/icon.ico

	Line#
	083: {
	084: Menu,Tray,DeleteAll
	085: Menu,Options_Tray,Delete
	086: Menu,Tools_Tray,Delete
	087: Menu,Maintanence_Tray,Delete
	088: Menu,Help_Tray,Delete
	089: }
--->	092: Menu,Tray,Icon,mainIconPath
	093: Menu,Tray,NoStandard
	094: Menu,Tray,Add,TXT.ABT__name " " PROGNAME,main
	095: Menu,Tray,Tip,PROGNAME " {" CN.Name "}"
	096: Menu,Tray,Add
	097: Menu,Tray,Add,TXT.SET_actmd "	" Hparse_Rev(actionmode_k),actionmode
	098: Menu,Tray,Add
	099: Menu,Maintanence_Tray,Add,TXT.PLG_delFileFolder,plugin_deleteFileFolder

The current thread will exit.
---------------------------
OK   
---------------------------

**Comment by hoppfrosch** [comment]
http://sourceforge.net/projects/clipjump/files/Clipjump_11.6.1.zip/download:  does not work as well, same behaviour


-------------------
Hint: clipjump.ahk (from this zip) does not run out of the box, due to following error (no need for fixing, just a hint to avoid in future versions)

---------------------------
Clipjump.ahk
---------------------------
Error in #include file "D:\Temp\Clipjump\lib\aboutgui.ahk":
     Can't load icon.

Specifically: icons/icon.ico

	Line#
	083: {
	084: Menu,Tray,DeleteAll
	085: Menu,Options_Tray,Delete
	086: Menu,Tools_Tray,Delete
	087: Menu,Maintanence_Tray,Delete
	088: Menu,Help_Tray,Delete
	089: }
--->	092: Menu,Tray,Icon,mainIconPath
	093: Menu,Tray,NoStandard
	094: Menu,Tray,Add,TXT.ABT__name " " PROGNAME,main
	095: Menu,Tray,Tip,PROGNAME " {" CN.Name "}"
	096: Menu,Tray,Add
	097: Menu,Tray,Add,TXT.SET_actmd "	" Hparse_Rev(actionmode_k),actionmode
	098: Menu,Tray,Add
	099: Menu,Maintanence_Tray,Add,TXT.PLG_delFileFolder,plugin_deleteFileFolder

The current thread will exit.
---------------------------
OK   
---------------------------

**Comment by aviaryan** [comment]
Thanks. I will have to use a gui I guess as I can't explain the situation that leads to the bug.

**Comment by aviaryan** [comment]
I will leave this issue open for some time.
