### ISSUE TITLE
Remove Fixate

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Clipjump#85]
The Fixate feature is buggy and I believe very rarely used.
The main purpose of fixate that is fixing a clip at one place so that its clip number doesn't change. Now a clip's content can be retrieved by `getClipDataByTag()`. I will add other API functions to enable users get more info of a *tagged* clip.

**Comment by Gabr-F** [comment]
If you mean the spacebar '[FIXED]' feature please don't remove it, it's extremely important for my workflow.

I actually don't understand how you can see it of little use, to me it appears fundamental for what's probably the core feature of the software, that is pasting the same string in a lot of places while maintaining the ability to copy and paste other stuff.

If you don't fixate the clip that you need it will be pushed further deep in the history each time you copy something, making it harder and more cumbersome to use as time passes.

-

Personally I learned to always place the fixed clips beyond the first position, so that the normal copy and paste doesn't get hampered. To do that I usually simply copy the clip I want to fix multiple times (usually 2) until one instance ends in the wanted position.

---

This would be less useful if the software had a way to easily assign shortcuts to particular clips, as I think most other clipboard managers have.

---

Fixing the bugs would be very welcome though ;)

I don't really know the source code but I have a feeling that you'd eradicate most bugs, and prevent a lot of future ones, by switching to a proper database management system for storing the clips.

**Comment by aviaryan** [comment]
> If you mean the spacebar '[FIXED]' feature please don't remove it, it's extremely important for my workflow.

One reason I am keen to remove this feature is because it has lots of issues. But you are right and maybe my workflow is different from yours, I don't really use this feature these days. But now when I think of it, I believe FIXATE feature can prove really helpful it it becomes bug-free .

> I don't really know the source code but I have a feeling that you'd eradicate most bugs, and prevent a lot of future ones, by switching to a proper database management system for storing the clips.

Yes you are right. Using a database will make things much cleaner and easier to manage... I will try doing this with 'Clipboard History' sometime (as it will be simpler). If it works well, I will implement it with channel and clips.

**Comment by aviaryan** [comment]
> I'm very little surprised when I find that some clip disappeared from some channel

I am sure that happens due to mis-management of clip files when some clip is deleted or moved or fixed.  Using a db will help fix these type of issues.

**Comment by aviaryan** [comment]
Idea dropped
